CREATE PROFILE HARDWARE_BASE_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

CREATE ROLE SYSADMIN_ROLE;
GRANT CREATE SESSION TO SYSADMIN_ROLE;
GRANT EXECUTE ANY PROCEDURE TO SYSADMIN_ROLE;
GRANT CREATE SEQUENCE TO SYSADMIN_ROLE;
GRANT EXECUTE ON HardwareAdminPackage TO SYSADMIN_ROLE;

CREATE ROLE CLIENT_ROLE;
GRANT CREATE SESSION TO CLIENT_ROLE;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO CLIENT_ROLE;
GRANT EXECUTE ON GamesClientPackage TO C##CLIENT_ROLE;

CREATE USER SYSADMIN IDENTIFIED BY PUK
    PROFILE HARDWARE_BASE_PROFILE
    ACCOUNT UNLOCK;
GRANT SYSADMIN_ROLE TO SYSADMIN;

CREATE USER SHOP_CLIENT IDENTIFIED BY PUK
  PROFILE HARDWARE_BASE_PROFILE
  ACCOUNT UNLOCK;
GRANT C##CLIENT_ROLE TO C##SHOP_CLIENT;
